services:
  clearpass_devices:
    build: .
    env_file:
    - ./.env
    volumes:
      - static_volume:/home/app/static
    depends_on:
    - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432

  nginx:
    build: ./nginx
    volumes:
    - static_volume:/home/app/static

    ports:
      - ${WEB_PORT:-80}:80
      - ${WEB_HTTPS_PORT:-443}:443
    depends_on:
      - clearpass_devices

volumes:
  postgres_data:
  static_volume: