services:
  clearpass_devices:
    image: datagutten/clearpass-device-db:latest
    env_file:
    - ./.env
    depends_on:
    - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${SQL_USER}
      PGUSER: ${SQL_USER} # Must be set for scripts to work
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
      PGDATABASE: ${SQL_DATABASE} # Must be set for scripts to work
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"

  nginx:
    image: datagutten/clearpass-device-db-nginx:latest

    ports:
      - ${WEB_PORT:-80}:80
      - ${WEB_HTTPS_PORT:-443}:443
    depends_on:
      - clearpass_devices

volumes:
  postgres_data:
  static_volume: